#!/bin/bash

# ----------
# display the status of all services
# ----------

display() {
  local service=$1

  systemctl is-active --quiet $service
  if [ $? -eq 0 ]; then
    local status="\033[32mRunning\033[0m"
  else
    local status="\033[31mNot Running\033[0m"
  fi

  printf "%-30s %b\n" "$service" "$status"
}

services=$(systemctl list-unit-files --type=service --no-legend --no-pager | awk '{print $1}' | sed 's/.service//' | grep -v '@')

for service in $services; do
  display $service
done
